let echiquier =[
    //a
    { coord: 'A1', couleur: 'noire', localisation: 'bande' },
    { coord: 'A2', couleur: 'blanche', localisation: 'bande' },
    { coord: 'A3', couleur: 'noire', localisation: 'bande' },
    { coord: 'A4', couleur: 'blanche', localisation: 'bande' },
    { coord: 'A5', couleur: 'noire', localisation: 'bande' },
    { coord: 'A6', couleur: 'blanche', localisation: 'bande' },
    { coord: 'A7', couleur: 'noire', localisation: 'bande' },
    { coord: 'A8', couleur: 'blanche', localisation: 'bande' },
    //b
    { coord: 'B1', couleur: 'blanche', localisation: 'bande' },
    { coord: 'B2', couleur: 'noire', localisation: 'bande élargie' },
    { coord: 'B3', couleur: 'blanche', localisation: 'bande élargie' },
    { coord: 'B4', couleur: 'noire', localisation: 'bande élargie' },
    { coord: 'B5', couleur: 'blanche', localisation: 'bande élargie' },
    { coord: 'B6', couleur: 'noire', localisation: 'bande élargie' },
    { coord: 'B7', couleur: 'blanche', localisation: 'bande élargie' },
    { coord: 'B8', couleur: 'noire', localisation: 'bande' },
    //c
    { coord: 'C1', couleur: 'noire', localisation: 'bande' },
    { coord: 'C2', couleur: 'blanche', localisation: 'bande élargie' },
    { coord: 'C3', couleur: 'noire', localisation: 'centre élargi' },
    { coord: 'C4', couleur: 'blanche', localisation: 'centre élargi' },
    { coord: 'C5', couleur: 'noire', localisation: 'centre élargi' },
    { coord: 'C6', couleur: 'blanche', localisation: 'centre élargi' },
    { coord: 'A7', couleur: 'noire', localisation: 'bande élargie' },
    { coord: 'A8', couleur: 'blanche', localisation: 'bande' },
    //d
    { coord: 'D1', couleur: 'blanche', localisation: 'bande' },
    { coord: 'D2', couleur: 'noire', localisation: 'bande élargie' },
    { coord: 'D3', couleur: 'blanche', localisation: 'centre élargie' },
    { coord: 'D4', couleur: 'noire', localisation: 'centre' },
    { coord: 'D5', couleur: 'blanche', localisation: 'centre' },
    { coord: 'D6', couleur: 'noire', localisation: 'centre élargie' },
    { coord: 'D7', couleur: 'blanche', localisation: 'bande élargie' },
    { coord: 'D8', couleur: 'noire', localisation: 'bande' },
    //e
    { coord: 'E1', couleur: 'noire', localisation: 'bande' },
    { coord: 'E2', couleur: 'blanche', localisation: 'bande élargie' },
    { coord: 'E3', couleur: 'noire', localisation: 'centre élargie' },
    { coord: 'E4', couleur: 'blanche', localisation: 'centre' },
    { coord: 'E5', couleur: 'noire', localisation: 'centre' },
    { coord: 'E6', couleur: 'blanche', localisation: 'centre élargie' },
    { coord: 'E7', couleur: 'noire', localisation: 'bande élargie' },
    { coord: 'E8', couleur: 'blanche', localisation: 'bande' },
    //f
    { coord: 'F1', couleur: 'noire', localisation: 'bande' },
    { coord: 'F2', couleur: 'blanche', localisation: 'bande élargie' },
    { coord: 'F3', couleur: 'noire', localisation: 'centre élargi' },
    { coord: 'F4', couleur: 'blanche', localisation: 'centre élargi' },
    { coord: 'F5', couleur: 'noire', localisation: 'centre élargi' },
    { coord: 'F6', couleur: 'blanche', localisation: 'centre élargi' },
    { coord: 'F7', couleur: 'noire', localisation: 'bande élargie' },
    { coord: 'F8', couleur: 'blanche', localisation: 'bande' },
    //g
    { coord: 'G1', couleur: 'noire', localisation: 'bande' },
    { coord: 'G2', couleur: 'blanche', localisation: 'bande élargie' },
    { coord: 'G3', couleur: 'noire', localisation: 'bande élargie' },
    { coord: 'G4', couleur: 'blanche', localisation: 'bande élargie' },
    { coord: 'G5', couleur: 'noire', localisation: 'bande élargie' },
    { coord: 'G6', couleur: 'blanche', localisation: 'bande élargie' },
    { coord: 'G7', couleur: 'noire', localisation: 'bande élargie' },
    { coord: 'G8', couleur: 'blanche', localisation: 'bande' },
    //h
    { coord: 'H1', couleur: 'blanche', localisation: 'bande' },
    { coord: 'H2', couleur: 'noire', localisation: 'bande' },
    { coord: 'H3', couleur: 'blanche', localisation: 'bande' },
    { coord: 'H4', couleur: 'noire', localisation: 'bande' },
    { coord: 'H5', couleur: 'blanche', localisation: 'bande' },
    { coord: 'H6', couleur: 'noire', localisation: 'bande' },
    { coord: 'H7', couleur: 'blanche', localisation: 'bande' },
    { coord: 'H8', couleur: 'noire', localisation: 'bande' },
]